version: '2'
services:
    learnerapp-app:
        image: learnerapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://learnerapp-postgresql:5432/learnerapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    learnerapp-postgresql:
        extends:
            file: postgresql.yml
            service: learnerapp-postgresql
